#!/usr/bin/env python

import sys

import string

majorversion = int(string.split(sys.version, ' ')[0][0])
minorversion = int(string.split(sys.version, ' ')[0][2])

if (majorversion < 2) or (majorversion == 2 and minorversion < 3):
    import os
    pythonlist = [  'python2.3',
                    'python23',
                    'python2.4',
                    'python24']
                    
    pythondirs = ['/usr/local/bin/', '/usr/bin/']
    
    for bin in pythonlist:
        for dir in pythondirs:                  
            binary = dir + bin
            if os.path.exists(binary):              
                os.system(binary + ' ' + string.join(sys.argv, ' '))
                sys.exit(0)
    print 'This version of Animail requires Python 2.0 or newer, no suitable version found'
    sys.exit(1)

sys.path.append("/usr/lib/animail")
sys.path.append("/usr/local/lib/animail")

from general import PROG_HOME
import gettext
gettext.bindtextdomain('animail', '/usr/share/locale/')
gettext.textdomain('animail')

import AnimailMain
AnimailMain.Application.run(sys.argv)

